name: Automated Release (pnpm)

on:
  push:
    branches:
      - main

jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'chore(release)')"
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Instalar pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.10.0

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.16.0
          cache: 'pnpm'

      - name: Instalar dependencias
        run: pnpm install

      - name: Configurar Git para el Bot
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump Version & Generate Tag
        id: tag_version
        run: |
          # Usamos pnpx para ejecutar standard-version
          pnpx standard-version

          # Extraemos la versión para el siguiente paso
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "version=v$NEW_VERSION" >> $GITHUB_OUTPUT

          git push --follow-tags origin main

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.version }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
